# Generated by Django 2.2.2 on 2019-06-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueName', models.CharField(max_length=255)),
                ('league_logo_url', models.CharField(max_length=400)),
                ('sport', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamCity', models.CharField(max_length=255)),
                ('teamName', models.CharField(max_length=255)),
                ('team_logo_url', models.CharField(max_length=400)),
                ('sport', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('championships', models.IntegerField(max_length=3)),
                ('wins', models.IntegerField(max_length=3)),
                ('losses', models.IntegerField(max_length=3)),
                ('standing', models.CharField(max_length=10)),
                ('favorite', models.BooleanField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='playoffs_app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=255)),
                ('player_photo_url', models.CharField(max_length=400)),
                ('sport', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('favorite', models.BooleanField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='playoffs_app.League')),
            ],
        ),
    ]
