# Generated by Django 2.2.2 on 2019-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playoffs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='championships',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
