# Generated by Django 2.2.2 on 2019-06-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playoffs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='championships',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
        migrations.RemoveField(
            model_name='team',
            name='standing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamCity',
        ),
        migrations.AddField(
            model_name='league',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='playoffs_app.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
